version: "3.1"
services:
  zookeeper:
    image: zookeeper
    container_name: "zookeeper"
    ports:
      - 2181:2181
  kafka:
    image: "bitnami/kafka:latest"
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  postgres:
    image: postgres:13-alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: "pgadmin"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #     - PGADMIN_LISTEN_PORT=80
  #   ports:
  #     - 15432:80
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   depends_on:
  #     - postgres
volumes:
  postgres:
 # pgadmin:
